### ISSUE TITLE
Serverstarter failing to download mods

### ISSUE THREAD

**Issue by madbrad21** [Yoosk/ServerStarter#4]
I started a server but nobody can connect

I did some more troubleshooting, it appears the startserver.bat runs but fails to download any of the add-ons
The mods folder after it runs only show krypton and servercore and no other mods

Below is the message that appears over and over as it starts up. The server does still stat once complete but obviously does not work with the modpack it is supposed to.

[12:17:19] [ERROR] Error while trying to get URL from cursemeta for mod ModEntryRaw(projectID=431823, fileID=3568648)

java.io.IOException: Request to https://cursemeta.dries007.net/431823/3568648.json was not successful.
at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType.downloadMods$lambda-3(CursePackType.kt:203)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Yoosk** [comment]
Sorry but curseforge changed their API and basically closed off any third party tool or launcher so this will no longer work.
